---
version: 2.1
jobs:
  test:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run:
          name: Setup ENV
          command: |
            timestamp=`date "+%s"`
            echo $CIRCLE_BRANCH-$timestamp
            echo $CIRCLE_TAG-$timestamp

workflows:
  version: 2
  test-circle:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
