---
version: 2.1
jobs:
  test:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run:
          name: Setup ENV
          command: |
            timestamp=`date "+%s"`
            if [[ "$CIRCLE_BRANCH" == "" ]] then $CIRCLE_TAG-$timestamp; else $CIRCLE_BRANCH-$timestamp; fi

workflows:
  version: 2
  test-circle:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
